CREATE SEQUENCE counter;

SELECT nextval('counter');

DROP SEQUENCE counter;

CREATE SEQUENCE counter INCREMENT BY 2 MINVALUE 0;

ALTER TABLE films ADD COLUMN id serial PRIMARY KEY;

ALTER TABLE films ADD COLUMN another_id serial PRIMARY KEY;

ALTER TABLE films DROP CONSTRAINT films_pkey;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'films';